### ISSUE TITLE
Weird Results on Larger Displays with Wide Console Window

### ISSUE THREAD

**Issue by paulhocker** [DerellLicht/ndir32#1]
Hello. I recently stumbled onto your awesome program for displaying directories on the command line. Thank you for making this.

I seem to be having an issue on a very large terminal window (> 151 chars wide) the display seems to be scattered almost like it gets confused about the size of the terminal.

I have tried this on both regular dos prompt, and also using the new Terminal app from Microsoft.

151x40
![image](https://user-images.githubusercontent.com/2214652/196286133-ff440d69-4583-4b4b-8985-90a6170e12a7.png)

152x40
![image](https://user-images.githubusercontent.com/2214652/196286284-bef4021b-7114-4012-8386-d8cb425ed6b8.png)

Wondering if you might have some thoughts around this.

Thanks. Great Tool!

**Comment by DerellLicht** [comment]
Hi @paulhocker !!!  
Sorry for the delay in responding to this!!  I don't come by here very often any more...
I will look into this and get back to you...

**Comment by DerellLicht** [comment]
Note that this bug is *not* present in 32-bit build, only in 64-bit build.  Apparently something is slightly different in the WinAPI Console library in 64-bit build.

[ heh... of course, the bug *was* present in the 32-bit build as well... don't know why it didn't fail in that case... ]

**Comment by paulhocker** [comment]
No worries. Glad you got it and hope you find a fix. I am not a c++ person so I did not know where to even start figuring it out.

:)

**Comment by paulhocker** [comment]
also, using the -W switch does not work for me

**Comment by paulhocker** [comment]
duh, because you said use -m :)

that switch works, thank!

**Comment by DerellLicht** [comment]
Okay, this bug is fixed in V2.56... It was a buffer overrun, unbelievably, in a 30-year-old program... I had never anticipated that the console would be wider than 132 characters!!  Now it supports consoles up to 1024 characters wide - and it tests for overrun...

Executable file is available here:
https://www.derelllicht.com/ndir_info.html
